# version: "3.9"
# services:
#   backend:
#     build: ./backend
#     ports:
#       - "4000:4000"
#     environment:
#       - MONGO_URI=mongodb://mongo:27017/toydb
#     depends_on:
#       - mongo

#   frontend:
#     build: ./frontend
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend

#   mongo:
#     image: mongo:7
#     ports:
#       - "27017:27017"
