apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: toy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: toy-frontend:dev
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://backend:4000"
