name: Dev CI/CD for Toy-Service

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker to use Minikube
        run: |
          echo "Setting Docker environment to Minikube"
          eval $(minikube docker-env)

      - name: Build Backend Docker Image
        run: docker build -t toy-backend:dev ./backend

      - name: Build Frontend Docker Image
        run: docker build -t toy-frontend:dev ./frontend

      - name: Configure Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
          kubectl config use-context minikube
          kubectl get nodes

      - name: Deploy MongoDB
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml

      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Verify Deployment
        run: |
          echo "Pods:"
          kubectl get pods
          echo "Services:"
          kubectl get svc
