name: Prod CI/CD for Toy-Service

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Backend Docker Image
      run: docker build -t ghcr.io/jovanatrajcheska/toy-backend:prod ./backend

    - name: Build Frontend Docker Image
      run: docker build -t ghcr.io/jovanatrajcheska/toy-frontend:prod ./frontend

    - name: Push Docker Images
      run: |
        docker push ghcr.io/jovanatrajcheska/toy-backend:prod
        docker push ghcr.io/jovanatrajcheska/toy-frontend:prod

    - name: Configure Kubernetes
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config
        kubectl config use-context minikube

    - name: Deploy to Prod Namespace
      run: |
        kubectl apply -f k8s/mongo-deployment.yaml -n toy-app
        kubectl apply -f k8s/mongo-service.yaml -n toy-app
        kubectl apply -f k8s/backend-deployment.yaml -n toy-app
        kubectl apply -f k8s/backend-service.yaml -n toy-app
        kubectl apply -f k8s/frontend-deployment.yaml -n toy-app
        kubectl apply -f k8s/frontend-service.yaml -n toy-app
