name: Dev CI/CD for Toy-Service

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Configure Docker to use Minikube
        shell: powershell
        run: minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Backend Docker Image
        run: docker build -t toy-backend:dev ./backend

      - name: Tag and Push Backend
        run: docker tag toy-backend:dev ghcr.io/jovanatrajcheska/toy-backend:dev
      - run: docker push ghcr.io/jovanatrajcheska/toy-backend:dev

      - name: Build Frontend Docker Image
        run: docker build -t toy-frontend:dev ./frontend

      - name: Tag and Push Frontend
        run: docker tag toy-frontend:dev ghcr.io/jovanatrajcheska/toy-frontend:dev
      - run: docker push ghcr.io/jovanatrajcheska/toy-frontend:dev

      - name: Configure Kubernetes
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path $HOME\.kube
          Set-Content -Path $HOME\.kube\config -Value "${{ secrets.KUBECONFIG_CONTENT }}"
          kubectl config use-context minikube
          kubectl get nodes

      - name: Deploy MongoDB
        run: |
          kubectl apply -f k8s/mongo-deployment.yaml
          kubectl apply -f k8s/mongo-service.yaml

      - name: Deploy Backend
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml

      - name: Deploy Frontend
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
